import { NextResponse } from 'next/server';
import { getPrisma } from '@/lib/prisma';

export async function GET() {
  try {
    const prisma = getPrisma();
    
    // Clear existing projects to make the analytics clean and consistent
    await prisma.project.deleteMany();
    
    const getPastDate = (monthsAgo: number, dayOffset: number = 0) => {
      const d = new Date();
      d.setMonth(d.getMonth() - monthsAgo);
      if (dayOffset !== 0) {
        d.setDate(d.getDate() - dayOffset);
      }
      return d;
    };
    
    const projectsData = [
      {
        name: 'Educational Institution Management System (EIMS)',
        description: '<p>Centralized hub to manage student enrollment, grading, course curation, billing, and parental notifications.</p>',
        type: 'Web UI Design',
        projectType: 'UI/UX Design',
        status: 'Ready for Deployment',
        priority: 'Critical',
        effort: 'XL',
        device: 'Desktop',
        owner: 'Raisul R.',
        company: 'MNTech Digital',
        startDate: '2026-01-10',
        endDate: '2026-05-15',
        deadline: '2026-06-30',
        clientName: 'Barisal Home Economics College',
        clientEmail: 'bhec.edu.bd@gmail.com',
        clientPhone: '01870802690',
        previewLink: 'https://figma.com/design/eims-design-mockup',
        shortOverview: 'All-in-one institutional management portal to digitize administrative operations and grading workflows.',
        businessGoal: 'Improve operational efficiency, eliminate paper billing, and establish transparent online parental reports.',
        targetAudience: 'College Administrators, Teachers, and Staff.',
        competitors: 'PowerSchool, Blackbaud, Fedena',
        tags: ['ERP', 'School Management', 'Web Portal', 'Education'],
        createdAt: getPastDate(5, 5),
      },
      {
        name: 'EIMS Student Portal Mobile App',
        description: '<p>Mobile companion app for students to keep track of schedules, view grades, and check attendance in real-time.</p>',
        type: 'Android App',
        projectType: 'Mobile App Development',
        status: 'In Progress',
        priority: 'High',
        effort: 'L',
        device: 'Mobile',
        owner: 'Sajid A.',
        company: 'MNTech Digital',
        startDate: '2026-02-15',
        deadline: '2026-07-20',
        clientName: 'Barisal Home Economics College',
        clientEmail: 'bhec.edu.bd@gmail.com',
        shortOverview: 'Dedicated Android application supporting real-time academic calendar notifications and homework submissions.',
        tags: ['Android', 'EdTech', 'App', 'Students'],
        createdAt: getPastDate(4, 12),
      },
      {
        name: 'EIMS Teacher Dashboard & Grading Panel',
        description: '<p>A highly interactive dashboard designed for educators to easily submit report card grades and log student attendance.</p>',
        type: 'Dashboard',
        projectType: 'Web Development',
        status: 'Review',
        priority: 'Medium',
        effort: 'M',
        device: 'Tablet',
        owner: 'Mahmud H.',
        company: 'MNTech Digital',
        startDate: '2026-03-01',
        endDate: '2026-05-30',
        deadline: '2026-06-25',
        clientName: 'Barisal Home Economics College',
        shortOverview: 'Responsive teacher dashboard layout with CSV grading exports and automated student progress flags.',
        tags: ['Dashboard', 'React', 'Full-Stack', 'Teachers'],
        createdAt: getPastDate(3, 8),
      },
      {
        name: 'Parent-Teacher Communication Hub',
        description: '<p>Cross-platform notification app allowing direct messaging, announcement broadcasts, and meeting schedulers.</p>',
        type: 'iOS App',
        projectType: 'Mobile App Development',
        status: 'Planning',
        priority: 'Critical',
        effort: 'M',
        device: 'Mobile',
        owner: 'Fahim K.',
        company: 'MNTech Digital',
        startDate: '2026-04-01',
        deadline: '2026-08-15',
        shortOverview: 'Dedicated push-notification engine for instant school notices and individual parent chat rooms.',
        tags: ['iOS', 'Push Notifications', 'Real-time Chat', 'Parents'],
        createdAt: getPastDate(2, 4),
      },
      {
        name: 'Barisal College Public Website',
        description: '<p>A modern, responsive public relations website presenting courses, faculty profiles, and admission guidelines.</p>',
        type: 'Landing Page',
        projectType: 'Web Development',
        status: 'Completed',
        priority: 'Low',
        effort: 'S',
        device: 'Desktop',
        owner: 'Nabila S.',
        company: 'MNTech Digital',
        startDate: '2026-01-05',
        endDate: '2026-02-28',
        previewLink: 'https://bhec.edu.bd',
        shortOverview: 'Public admission website featuring virtual campus tours and SEO-optimized search for degree programs.',
        tags: ['Website', 'SEO', 'Tailwind', 'Nextjs'],
        createdAt: getPastDate(5, 20),
      },
      {
        name: 'EIMS Automated Fee Payment Gateway',
        description: '<p>Integrating local payment channels (bKash, Nagad, SSLCommerz) to collect tuition fees and generate digital invoices.</p>',
        type: 'Payment Gateway Integration',
        projectType: 'Web Development',
        status: 'In Testing',
        priority: 'Critical',
        effort: 'L',
        device: 'All',
        owner: 'Anik D.',
        company: 'MNTech Digital',
        startDate: '2026-05-01',
        deadline: '2026-07-05',
        shortOverview: 'Automated billing microservice that emails PDF receipts to parents immediately upon bKash checkout.',
        tags: ['Fintech', 'bKash', 'Nagad', 'API Integration'],
        createdAt: getPastDate(1, 2),
      },
      {
        name: 'Executive Analytics System',
        description: '<p>Business intelligence dashboards to monitor enrollment stats, profit margins, and departmental budgets.</p>',
        type: 'Dashboard',
        projectType: 'Web Development',
        status: 'Research',
        priority: 'High',
        effort: 'XL',
        device: 'Desktop',
        owner: 'Raisul R.',
        company: 'MNTech Digital',
        startDate: '2026-01-01',
        deadline: '2026-06-01',
        shortOverview: 'Interactive charts and forecasting algorithms displaying school financial health metrics to the board of directors.',
        tags: ['Analytics', 'Business Intelligence', 'Docker', 'Postgres'],
        createdAt: getPastDate(5, 28),
      },
      {
        name: 'EIMS Mobile Design System (DS)',
        description: '<p>Unified Figma components, variables, typography grids, and theme settings to accelerate mobile design.</p>',
        type: 'Design System',
        projectType: 'UI/UX Design',
        status: 'Completed',
        priority: 'Medium',
        effort: 'M',
        device: 'None',
        owner: 'Nabila S.',
        company: 'MNTech Digital',
        startDate: '2026-02-01',
        endDate: '2026-03-15',
        previewLink: 'https://figma.com/design/eims-mobile-ds',
        shortOverview: 'Standardized UI kit offering consistent buttons, input controls, and dark-mode styles.',
        tags: ['Design System', 'Figma', 'UI Kit', 'Style Guide'],
        createdAt: getPastDate(4, 1),
      },
      {
        name: 'EIMS Virtual Classroom WebRTC Integration',
        description: '<p>Enabling direct virtual classroom calls, screen sharing, and audio board within the browser.</p>',
        type: 'API Integration',
        projectType: 'Web Development',
        status: 'Planning',
        priority: 'High',
        effort: 'XL',
        device: 'Desktop',
        owner: 'Sajid A.',
        company: 'MNTech Digital',
        startDate: '2026-04-10',
        deadline: '2026-09-01',
        shortOverview: 'Integrating live WebRTC video channels inside student course pages with whiteboard overlays.',
        tags: ['WebRTC', 'Live Video', 'API', 'Interactive'],
        createdAt: getPastDate(2, 15),
      },
      {
        name: 'EIMS Library Book Tracker',
        description: '<p>Cross-platform application built for tablets to scan library barcodes, log rentals, and automate return alerts.</p>',
        type: 'Cross-Platform App',
        projectType: 'Mobile App Development',
        status: 'In Progress',
        priority: 'Low',
        effort: 'M',
        device: 'Tablet',
        owner: 'Mahmud H.',
        company: 'MNTech Digital',
        startDate: '2026-03-15',
        deadline: '2026-07-15',
        shortOverview: 'Scan barcodes using device camera to instantly lookup books and log due dates.',
        tags: ['Barcode Scanner', 'Library', 'Flutter', 'SQLite'],
        createdAt: getPastDate(3, 22),
      },
      {
        name: 'EIMS Identity Pack & Brand Logo',
        description: '<p>Design audit, typography guide, color palette definition, and vector icon collections for official branding.</p>',
        type: 'Icon Set',
        projectType: 'UI/UX Design',
        status: 'Completed',
        priority: 'Optional',
        effort: 'S',
        device: 'None',
        owner: 'Fahim K.',
        company: 'MNTech Digital',
        startDate: '2026-01-02',
        endDate: '2026-01-20',
        shortOverview: 'Standardizing official brand identity, business cards, and customized vectors for EIMS marketing.',
        tags: ['Logo', 'Branding', 'Vector Art', 'Illustrator'],
        createdAt: getPastDate(5, 29),
      },
      {
        name: 'GraphQL API Gateway Infrastructure',
        description: '<p>High-performance federated graph API managing queries from both Web portals and Mobile client apps.</p>',
        type: 'GraphQL API',
        projectType: 'Web Development',
        status: 'Maintenance',
        priority: 'Critical',
        effort: 'L',
        device: 'All',
        owner: 'Anik D.',
        company: 'MNTech Digital',
        startDate: '2026-05-10',
        deadline: '2026-06-15',
        shortOverview: 'Apollo Federation setup to resolve database queries across student, teacher, and financial servers.',
        tags: ['GraphQL', 'Apollo', 'Microservices', 'Infra'],
        createdAt: getPastDate(1, 10),
      },
      {
        name: 'Interactive LMS Math Game',
        description: '<p>Gamified quizzes and mathematics puzzles inside the student app to encourage daily exercises.</p>',
        type: 'Mobile Game',
        projectType: 'Mobile App Development',
        status: 'Ready for Deployment',
        priority: 'Medium',
        effort: 'M',
        device: 'Mobile',
        owner: 'Sajid A.',
        company: 'MNTech Digital',
        startDate: '2026-04-01',
        endDate: '2026-05-25',
        deadline: '2026-06-10',
        shortOverview: 'Gamified mathematics application with online leaderboards and customized achievement badges.',
        tags: ['Gamification', 'Math', 'Unity', 'Kids Education'],
        createdAt: getPastDate(2, 28),
      },
      {
        name: 'Dockerized Local Environment Setup',
        description: '<p>Setting up Docker compose files and local databases to easily clone and run the EIMS environment locally.</p>',
        type: 'Docker Deployment',
        projectType: 'Web Development',
        status: 'Completed',
        priority: 'Urgent',
        effort: 'S',
        device: 'None',
        owner: 'Anik D.',
        company: 'MNTech Digital',
        startDate: '2026-03-01',
        endDate: '2026-03-25',
        shortOverview: 'One-click local docker orchestration setup to stand up PostgreSQL, Redis, and API endpoints.',
        tags: ['Docker', 'DevOps', 'Postgres', 'Local Dev'],
        createdAt: getPastDate(3, 10),
      },
      {
        name: 'EIMS User Journey Mapping & Audit',
        description: '<p>Comprehensive user research conducting usability tests and journey mapping for student admissions.</p>',
        type: 'Design Audit',
        projectType: 'UI/UX Design',
        status: 'Completed',
        priority: 'Medium',
        effort: 'M',
        device: 'All',
        owner: 'Raisul R.',
        company: 'MNTech Digital',
        startDate: '2026-01-15',
        endDate: '2026-02-28',
        shortOverview: 'User research documentation highlighting bottlenecks in student registrations and parent profile creations.',
        tags: ['User Research', 'Audit', 'Journey Mapping', 'Usability'],
        createdAt: getPastDate(5, 15),
      }
    ];

    // Insert projects
    for (const project of projectsData) {
      await prisma.project.create({
        data: {
          name: project.name,
          description: project.description,
          type: project.type,
          projectType: project.projectType,
          status: project.status,
          priority: project.priority,
          effort: project.effort,
          device: project.device,
          owner: project.owner,
          company: project.company,
          startDate: project.startDate || '',
          endDate: project.endDate || '',
          deadline: project.deadline || '',
          clientName: project.clientName || '',
          clientEmail: project.clientEmail || '',
          clientPhone: project.clientPhone || '',
          previewLink: project.previewLink || '',
          shortOverview: project.shortOverview || '',
          businessGoal: project.businessGoal || '',
          targetAudience: project.targetAudience || '',
          competitors: project.competitors || '',
          tags: project.tags,
          createdAt: project.createdAt,
        }
      });
    }

    return NextResponse.json({
      ok: true,
      message: `${projectsData.length} realistic projects successfully seeded into the database.`
    });
  } catch (error) {
    console.error('Seeding Error:', error);
    return NextResponse.json({ error: 'Failed to seed projects' }, { status: 500 });
  }
}
